In [18]:
import torch
torch.cuda.is_available()


True

In [19]:
torch.__version__

'2.5.1'

In [20]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [21]:
tensor = torch.tensor([1, 2, 3], device='cpu')
tensor

tensor([1, 2, 3])

In [22]:
tensor_on_gpu = torch.tensor([1, 2, 3], device=device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [23]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [17]:
to_back_on_cpu = torch.tensor([1, 2, 3], device='cpu')

to_back_on_cpu.numpy()

array([1, 2, 3])